// Copyright 2026 Chalindu Kodikara
// SPDX-License-Identifier: Apache-2.0

package header

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chalindukodikara/licenseops/internal/language"
)

// helper to write a temp file and return its path.
func writeTempFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// --- IsGenerated ---

func TestIsGenerated_CodeGenerated(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// Code generated by foo. DO NOT EDIT.\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true for 'Code generated ... DO NOT EDIT'")
	}
}

func TestIsGenerated_AtGenerated(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// @generated\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true for '@generated'")
	}
}

func TestIsGenerated_NoMarker(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false for normal file")
	}
}

func TestIsGenerated_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "empty.go", "")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false for empty file")
	}
}

func TestIsGenerated_MarkerBeyondLine30(t *testing.T) {
	dir := t.TempDir()
	var lines []string
	for i := 0; i < 35; i++ {
		lines = append(lines, "// normal line")
	}
	lines = append(lines, "// Code generated by foo. DO NOT EDIT.")
	p := writeTempFile(t, dir, "deep.go", strings.Join(lines, "\n"))
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false when marker is beyond line 30")
	}
}

func TestIsGenerated_CaseInsensitive(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// CODE GENERATED by tool. DO NOT EDIT.\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true for case-insensitive match")
	}
}

// --- ReadHeaderLines ---

func TestReadHeaderLines_SkipsShebang(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n# Copyright 2026 Acme\nprint('hello')\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 || strings.HasPrefix(lines[0], "#!") {
		t.Error("ReadHeaderLines should skip shebang")
	}
	if lines[0] != "# Copyright 2026 Acme" {
		t.Errorf("first line = %q, want %q", lines[0], "# Copyright 2026 Acme")
	}
}

func TestReadHeaderLines_SkipsPythonEncoding(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "# -*- coding: utf-8 -*-\n# Copyright 2026 Acme\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 {
		t.Fatal("expected lines")
	}
	if strings.Contains(lines[0], "coding") {
		t.Error("ReadHeaderLines should skip Python encoding declaration")
	}
}

func TestReadHeaderLines_SkipsBlanks(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "\n\n\n// Copyright 2026 Acme\npackage main\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 || lines[0] != "// Copyright 2026 Acme" {
		t.Errorf("expected first content line, got %v", lines)
	}
}

// --- Prepend ---

func TestPrepend_NormalFile(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	style := &language.Style{LinePrefix: "//"}
	hdr := "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT"
	format := &SPDXFormat{}

	if err := Prepend(p, style, hdr, format); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	if !strings.HasPrefix(content, "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT\n\npackage main") {
		t.Errorf("unexpected content:\n%s", content)
	}
}

func TestPrepend_PreservesShebang(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	hdr := "# Copyright 2026 Acme\n# SPDX-License-Identifier: MIT"
	format := &SPDXFormat{}

	if err := Prepend(p, style, hdr, format); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	if !strings.HasPrefix(content, "#!/usr/bin/env python3\n") {
		t.Error("shebang should be preserved at top")
	}
	if !strings.Contains(content, "# Copyright 2026 Acme") {
		t.Error("header should be present after shebang")
	}
}

func TestPrepend_PreservesPythonEncoding(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	hdr := "# Copyright 2026 Acme\n# SPDX-License-Identifier: MIT"
	format := &SPDXFormat{}

	if err := Prepend(p, style, hdr, format); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	lines := strings.Split(content, "\n")

	if lines[0] != "#!/usr/bin/env python3" {
		t.Errorf("line 0 = %q, want shebang", lines[0])
	}
	if lines[1] != "# -*- coding: utf-8 -*-" {
		t.Errorf("line 1 = %q, want encoding", lines[1])
	}
	// Header should appear after both
	if !strings.Contains(content, "# Copyright 2026 Acme") {
		t.Error("header should be present after shebang and encoding")
	}
}

func TestPrepend_CrossFormatMigration(t *testing.T) {
	dir := t.TempDir()
	// File has SPDX header, we prepend with REUSE format
	original := "// Copyright 2025 Old\n// SPDX-License-Identifier: MIT\n\npackage main\n"
	p := writeTempFile(t, dir, "main.go", original)
	style := &language.Style{LinePrefix: "//"}
	newHdr := "// SPDX-FileCopyrightText: 2026 Acme\n// SPDX-License-Identifier: MIT"
	format := &ReuseFormat{}

	if err := Prepend(p, style, newHdr, format); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	// Old header should be stripped
	if strings.Contains(content, "Copyright 2025 Old") {
		t.Error("old SPDX header should have been stripped")
	}
	// New header should be present
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 Acme") {
		t.Error("new REUSE header should be present")
	}
	if !strings.Contains(content, "package main") {
		t.Error("original code should be preserved")
	}
}

func TestPrepend_Idempotent(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n")
	style := &language.Style{LinePrefix: "//"}
	hdr := "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT"
	format := &SPDXFormat{}

	// Apply twice
	if err := Prepend(p, style, hdr, format); err != nil {
		t.Fatal(err)
	}
	if err := Prepend(p, style, hdr, format); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	count := strings.Count(content, "SPDX-License-Identifier")
	if count != 1 {
		t.Errorf("expected 1 SPDX line after double prepend, got %d", count)
	}
}

// --- FormatByName ---

func TestFormatByName_Valid(t *testing.T) {
	names := []string{"spdx", "", "reuse", "apache-long", "gpl-long", "custom"}
	for _, name := range names {
		f, err := FormatByName(name)
		if err != nil {
			t.Errorf("FormatByName(%q) error: %v", name, err)
		}
		if f == nil {
			t.Errorf("FormatByName(%q) returned nil", name)
		}
	}
}

func TestFormatByName_Invalid(t *testing.T) {
	_, err := FormatByName("nonexistent")
	if err == nil {
		t.Error("expected error for unknown format")
	}
}

// --- AllFormats ---

func TestAllFormats_Count(t *testing.T) {
	fmts := AllFormats()
	if len(fmts) != 4 {
		t.Errorf("AllFormats() returned %d formats, want 4", len(fmts))
	}
}
