// Copyright 2026 Chalindu Kodikara
// SPDX-License-Identifier: Apache-2.0

package header

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chalindukodikara/licenseops/internal/language"
)

func writeTempFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// --- IsGenerated ---

func TestIsGenerated_CodeGenerated(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// Code generated by foo. DO NOT EDIT.\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true")
	}
}

func TestIsGenerated_AtGenerated(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// @generated\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true")
	}
}

func TestIsGenerated_NoMarker(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false")
	}
}

func TestIsGenerated_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "empty.go", "")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false for empty file")
	}
}

func TestIsGenerated_MarkerBeyondLine30(t *testing.T) {
	dir := t.TempDir()
	var lines []string
	for range 35 {
		lines = append(lines, "// normal line")
	}
	lines = append(lines, "// Code generated by foo. DO NOT EDIT.")
	p := writeTempFile(t, dir, "deep.go", strings.Join(lines, "\n"))
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if got {
		t.Error("expected generated=false when marker beyond line 30")
	}
}

func TestIsGenerated_CaseInsensitive(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "gen.go", "// CODE GENERATED by tool. DO NOT EDIT.\npackage main\n")
	got, err := IsGenerated(p)
	if err != nil {
		t.Fatal(err)
	}
	if !got {
		t.Error("expected generated=true for case-insensitive match")
	}
}

// --- ReadHeaderLines ---

func TestReadHeaderLines_SkipsShebang(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n# Copyright 2026 Acme\nprint('hello')\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 || strings.HasPrefix(lines[0], "#!") {
		t.Error("ReadHeaderLines should skip shebang")
	}
}

func TestReadHeaderLines_SkipsPythonEncoding(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "# -*- coding: utf-8 -*-\n# Copyright 2026 Acme\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 {
		t.Fatal("expected lines")
	}
	if strings.Contains(lines[0], "coding") {
		t.Error("should skip encoding declaration")
	}
}

func TestReadHeaderLines_SkipsBlanks(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "\n\n\n// Copyright 2026 Acme\npackage main\n")
	lines, err := ReadHeaderLines(p, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) == 0 || lines[0] != "// Copyright 2026 Acme" {
		t.Errorf("expected first content line, got %v", lines)
	}
}

// --- Prepend ---

func TestPrepend_NormalFile(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	style := &language.Style{LinePrefix: "//"}
	hdr := "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT"
	if err := Prepend(p, style, hdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	if !strings.HasPrefix(string(data), "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT\n\npackage main") {
		t.Errorf("unexpected content:\n%s", data)
	}
}

func TestPrepend_PreservesShebang(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	hdr := "# Copyright 2026 Acme\n# SPDX-License-Identifier: MIT"
	if err := Prepend(p, style, hdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if !strings.HasPrefix(content, "#!/usr/bin/env python3\n") {
		t.Error("shebang should be preserved")
	}
	if !strings.Contains(content, "# Copyright 2026 Acme") {
		t.Error("header should be present")
	}
}

func TestPrepend_PreservesPythonEncoding(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	hdr := "# Copyright 2026 Acme\n# SPDX-License-Identifier: MIT"
	if err := Prepend(p, style, hdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	lines := strings.Split(string(data), "\n")
	if lines[0] != "#!/usr/bin/env python3" {
		t.Errorf("line 0 = %q, want shebang", lines[0])
	}
	if lines[1] != "# -*- coding: utf-8 -*-" {
		t.Errorf("line 1 = %q, want encoding", lines[1])
	}
}

func TestPrepend_CrossFormatMigration(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "// Copyright 2025 Old\n// SPDX-License-Identifier: MIT\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := "// SPDX-FileCopyrightText: 2026 Acme\n// SPDX-License-Identifier: MIT"
	if err := Prepend(p, style, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Copyright 2025 Old") {
		t.Error("old SPDX header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 Acme") {
		t.Error("new REUSE header should be present")
	}
}

func TestPrepend_CrossFormat_ReuseToSPDX(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "// SPDX-FileCopyrightText: 2025 OldCorp\n// SPDX-License-Identifier: MIT\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&SPDXFormat{}).Generate(style, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, style, newHdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "SPDX-FileCopyrightText") {
		t.Error("old REUSE header should have been stripped")
	}
	if !strings.Contains(content, "Copyright 2026 NewCorp") {
		t.Error("new SPDX copyright should be present")
	}
	if !strings.Contains(content, "SPDX-License-Identifier: Apache-2.0") {
		t.Error("new SPDX license should be present")
	}
	if !strings.Contains(content, "package main") {
		t.Error("code should be preserved")
	}
}

func TestPrepend_CrossFormat_ApacheToSPDX(t *testing.T) {
	dir := t.TempDir()
	apacheHdr := (&ApacheLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "Apache-2.0")
	p := writeTempFile(t, dir, "main.go", apacheHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&SPDXFormat{}).Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Apache License") {
		t.Error("old Apache header should have been stripped")
	}
	if !strings.Contains(content, "Copyright 2026 NewCorp") {
		t.Error("new SPDX copyright should be present")
	}
	if !strings.Contains(content, "SPDX-License-Identifier: MIT") {
		t.Error("new SPDX license should be present")
	}
	if strings.Count(content, "SPDX-License-Identifier") != 1 {
		t.Error("should have exactly one SPDX line")
	}
}

func TestPrepend_CrossFormat_GPLToSPDX(t *testing.T) {
	dir := t.TempDir()
	gplHdr := (&GPLLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "GPL-3.0-only")
	p := writeTempFile(t, dir, "main.go", gplHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&SPDXFormat{}).Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "GNU General Public License") {
		t.Error("old GPL header should have been stripped")
	}
	if !strings.Contains(content, "Copyright 2026 NewCorp") {
		t.Error("new SPDX copyright should be present")
	}
	if !strings.Contains(content, "package main") {
		t.Error("code should be preserved")
	}
}

func TestPrepend_CrossFormat_ApacheToReuse(t *testing.T) {
	dir := t.TempDir()
	apacheHdr := (&ApacheLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "Apache-2.0")
	p := writeTempFile(t, dir, "main.go", apacheHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&ReuseFormat{}).Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Apache License") {
		t.Error("old Apache header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
}

func TestPrepend_CrossFormat_GPLToReuse(t *testing.T) {
	dir := t.TempDir()
	gplHdr := (&GPLLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "AGPL-3.0-only")
	p := writeTempFile(t, dir, "main.go", gplHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&ReuseFormat{}).Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "GNU Affero") {
		t.Error("old AGPL header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
}

func TestPrepend_CrossFormat_SPDXToApache(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "// Copyright 2025 OldCorp\n// SPDX-License-Identifier: MIT\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&ApacheLongFormat{}).Generate(style, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, style, newHdr, &ApacheLongFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "OldCorp") {
		t.Error("old SPDX header should have been stripped")
	}
	if !strings.Contains(content, "Licensed under the Apache License") {
		t.Error("new Apache header should be present")
	}
	if !strings.Contains(content, "Copyright 2026 NewCorp") {
		t.Error("new copyright should be present")
	}
}

func TestPrepend_CrossFormat_SPDXToGPL(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "// Copyright 2025 OldCorp\n// SPDX-License-Identifier: MIT\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&GPLLongFormat{}).Generate(style, "2026", "NewCorp", "GPL-3.0-only")
	if err := Prepend(p, style, newHdr, &GPLLongFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "OldCorp") {
		t.Error("old SPDX header should have been stripped")
	}
	if !strings.Contains(content, "GNU General Public License") {
		t.Error("new GPL header should be present")
	}
}

func TestPrepend_CrossFormat_ApacheToGPL(t *testing.T) {
	dir := t.TempDir()
	apacheHdr := (&ApacheLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "Apache-2.0")
	p := writeTempFile(t, dir, "main.go", apacheHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&GPLLongFormat{}).Generate(style, "2026", "NewCorp", "GPL-3.0-only")
	if err := Prepend(p, style, newHdr, &GPLLongFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Apache License") {
		t.Error("old Apache header should have been stripped")
	}
	if !strings.Contains(content, "GNU General Public License") {
		t.Error("new GPL header should be present")
	}
}

func TestPrepend_CrossFormat_GPLToApache(t *testing.T) {
	dir := t.TempDir()
	gplHdr := (&GPLLongFormat{}).Generate(&language.Style{LinePrefix: "//"}, "2025", "OldCorp", "GPL-3.0-only")
	p := writeTempFile(t, dir, "main.go", gplHdr+"\n\npackage main\n")
	style := &language.Style{LinePrefix: "//"}
	newHdr := (&ApacheLongFormat{}).Generate(style, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, style, newHdr, &ApacheLongFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "GNU General Public License") {
		t.Error("old GPL header should have been stripped")
	}
	if !strings.Contains(content, "Licensed under the Apache License") {
		t.Error("new Apache header should be present")
	}
}

func TestPrepend_CrossFormat_WithShebang(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n\n# Copyright 2025 OldCorp\n# SPDX-License-Identifier: MIT\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	newHdr := (&ReuseFormat{}).Generate(style, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, style, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if !strings.HasPrefix(content, "#!/usr/bin/env python3\n") {
		t.Error("shebang should be preserved at the top")
	}
	if strings.Contains(content, "Copyright 2025 OldCorp") {
		t.Error("old SPDX header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
	if !strings.Contains(content, "print('hello')") {
		t.Error("code should be preserved")
	}
}

func TestPrepend_CrossFormat_WithPythonEncoding(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "script.py", "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\n# Copyright 2025 OldCorp\n# SPDX-License-Identifier: MIT\n\nprint('hello')\n")
	style := &language.Style{LinePrefix: "#"}
	newHdr := (&ReuseFormat{}).Generate(style, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, style, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	lines := strings.Split(string(data), "\n")
	if lines[0] != "#!/usr/bin/env python3" {
		t.Errorf("line 0 = %q, want shebang", lines[0])
	}
	if lines[1] != "# -*- coding: utf-8 -*-" {
		t.Errorf("line 1 = %q, want encoding", lines[1])
	}
	content := string(data)
	if strings.Contains(content, "Copyright 2025 OldCorp") {
		t.Error("old SPDX header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
}

func TestPrepend_CrossFormat_HashComments(t *testing.T) {
	dir := t.TempDir()
	style := &language.Style{LinePrefix: "#"}
	apacheHdr := (&ApacheLongFormat{}).Generate(style, "2025", "OldCorp", "Apache-2.0")
	p := writeTempFile(t, dir, "script.rb", apacheHdr+"\n\nputs 'hello'\n")
	newHdr := (&SPDXFormat{}).Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, &SPDXFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Apache License") {
		t.Error("old Apache header should have been stripped")
	}
	if !strings.Contains(content, "# Copyright 2026 NewCorp") {
		t.Error("new SPDX header should use # comment style")
	}
	if !strings.Contains(content, "puts 'hello'") {
		t.Error("code should be preserved")
	}
}

func TestPrepend_CrossFormat_BlockComments(t *testing.T) {
	dir := t.TempDir()
	blockStyle := &language.Style{BlockStart: "/*", BlockEnd: "*/"}
	spdxHdr := (&SPDXFormat{}).Generate(blockStyle, "2025", "OldCorp", "MIT")
	p := writeTempFile(t, dir, "style.css", spdxHdr+"\n\n.body { color: red; }\n")
	newHdr := (&ReuseFormat{}).Generate(blockStyle, "2026", "NewCorp", "Apache-2.0")
	if err := Prepend(p, blockStyle, newHdr, &ReuseFormat{}); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(p)
	content := string(data)
	if strings.Contains(content, "Copyright 2025 OldCorp") {
		t.Error("old SPDX block header should have been stripped")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
	if !strings.Contains(content, ".body { color: red; }") {
		t.Error("code should be preserved")
	}
}

func TestPrepend_CrossFormat_MigrationThenIdempotent(t *testing.T) {
	dir := t.TempDir()
	// Start with Apache
	style := &language.Style{LinePrefix: "//"}
	apacheHdr := (&ApacheLongFormat{}).Generate(style, "2025", "OldCorp", "Apache-2.0")
	p := writeTempFile(t, dir, "main.go", apacheHdr+"\n\npackage main\n")

	// Migrate to SPDX
	spdxFmt := &SPDXFormat{}
	newHdr := spdxFmt.Generate(style, "2026", "NewCorp", "MIT")
	if err := Prepend(p, style, newHdr, spdxFmt); err != nil {
		t.Fatal(err)
	}

	// Run Prepend again — should be idempotent
	if err := Prepend(p, style, newHdr, spdxFmt); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)
	if count := strings.Count(content, "SPDX-License-Identifier"); count != 1 {
		t.Errorf("expected 1 SPDX line after migration + re-run, got %d", count)
	}
	if strings.Contains(content, "Apache License") {
		t.Error("Apache header should not reappear")
	}
}

func TestPrepend_Idempotent(t *testing.T) {
	dir := t.TempDir()
	p := writeTempFile(t, dir, "main.go", "package main\n")
	style := &language.Style{LinePrefix: "//"}
	hdr := "// Copyright 2026 Acme\n// SPDX-License-Identifier: MIT"
	f := &SPDXFormat{}
	_ = Prepend(p, style, hdr, f)
	_ = Prepend(p, style, hdr, f)
	data, _ := os.ReadFile(p)
	if count := strings.Count(string(data), "SPDX-License-Identifier"); count != 1 {
		t.Errorf("expected 1 SPDX line, got %d", count)
	}
}

func TestFormatByName_Valid(t *testing.T) {
	for _, name := range []string{"spdx", "", "reuse", "apache-long", "gpl-long", "custom"} {
		f, err := FormatByName(name)
		if err != nil {
			t.Errorf("FormatByName(%q) error: %v", name, err)
		}
		if f == nil {
			t.Errorf("FormatByName(%q) returned nil", name)
		}
	}
}

func TestFormatByName_Invalid(t *testing.T) {
	_, err := FormatByName("nonexistent")
	if err == nil {
		t.Error("expected error for unknown format")
	}
}

func TestAllFormats_Count(t *testing.T) {
	if n := len(AllFormats()); n != 4 {
		t.Errorf("AllFormats() returned %d, want 4", n)
	}
}
