# Copyright 2026 Chalindu Kodikara
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style

    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
