// Copyright 2026 Chalindu Kodikara
// SPDX-License-Identifier: Apache-2.0

package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chalindukodikara/licenseops/internal/config"
)

func createFile(t *testing.T, dir, relPath, content string) string {
	t.Helper()
	full := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return full
}

func testConfig(dir string) config.Config {
	tr := true
	return config.Config{
		License:         "Apache-2.0",
		CopyrightHolder: "Acme Corp",
		Year:            "2026",
		Format:          "spdx",
		Paths:           []string{dir},
		SkipGenerated:   &tr,
		Gitignore:       &tr,
		Exclude:         []string{"vendor/**", "node_modules/**", ".git/**"},
	}
}

// --- Check ---

func TestCheck_AllCompliant(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	eng, _ := New(testConfig(dir))
	result, err := eng.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) > 0 {
		t.Errorf("expected 0 non-compliant, got %d", len(result.NonCompliant))
	}
}

func TestCheck_NonCompliant(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "good.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	createFile(t, dir, "bad.go", "package main\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.Check(false)
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant, got %d", len(result.NonCompliant))
	}
}

func TestCheck_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "gen.go", "// Code generated by tool. DO NOT EDIT.\npackage gen\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.Check(false)
	if len(result.NonCompliant) > 0 {
		t.Error("generated should be skipped")
	}
	if len(result.Skipped) != 1 {
		t.Errorf("expected 1 skipped, got %d", len(result.Skipped))
	}
}

// --- Fix ---

func TestFix_AddsHeaders(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if !strings.Contains(string(data), "SPDX-License-Identifier: Apache-2.0") {
		t.Error("file should have header after fix")
	}
}

func TestFix_LeavesCompliantUnchanged(t *testing.T) {
	dir := t.TempDir()
	original := "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n"
	createFile(t, dir, "main.go", original)
	eng, _ := New(testConfig(dir))
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) > 0 {
		t.Error("compliant file should not be fixed")
	}
}

func TestFix_DryRun(t *testing.T) {
	dir := t.TempDir()
	original := "package main\n"
	createFile(t, dir, "main.go", original)
	eng, _ := New(testConfig(dir))
	result, _ := eng.Fix(true, false)
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant, got %d", len(result.NonCompliant))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != original {
		t.Error("dry-run should not modify files")
	}
}

func TestFix_ThenCheck(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	createFile(t, dir, "lib.go", "package main\n")
	cfg := testConfig(dir)
	eng, _ := New(cfg)
	eng.Fix(false, false)
	eng2, _ := New(cfg)
	result, _ := eng2.Check(false)
	if len(result.NonCompliant) > 0 {
		t.Error("after fix, check should pass")
	}
}

func TestFix_MultipleCommentStyles(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	createFile(t, dir, "script.py", "print('hello')\n")
	createFile(t, dir, "query.sql", "SELECT 1;\n")
	cfg := testConfig(dir)
	cfg.License = "MIT"
	cfg.CopyrightHolder = ""
	eng, _ := New(cfg)
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 3 {
		t.Errorf("expected 3 fixed, got %d", len(result.Fixed))
	}
	goData, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	pyData, _ := os.ReadFile(filepath.Join(dir, "script.py"))
	sqlData, _ := os.ReadFile(filepath.Join(dir, "query.sql"))
	if !strings.HasPrefix(string(goData), "// SPDX") {
		t.Error("Go should use //")
	}
	if !strings.HasPrefix(string(pyData), "# SPDX") {
		t.Error("Python should use #")
	}
	if !strings.HasPrefix(string(sqlData), "-- SPDX") {
		t.Error("SQL should use --")
	}
}

// --- FixWithDiff ---

func TestFixWithDiff_ProducesDiff(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	eng, _ := New(testConfig(dir))
	result, err := eng.FixWithDiff(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant, got %d", len(result.NonCompliant))
	}
	if len(result.Diffs) == 0 {
		t.Error("expected diffs to be populated")
	}
	for _, d := range result.Diffs {
		if !strings.Contains(d, "SPDX-License-Identifier") {
			t.Error("diff should contain the new header")
		}
		if !strings.Contains(d, "---") || !strings.Contains(d, "+++") {
			t.Error("diff should look like unified diff")
		}
	}
	// File should NOT be modified
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != "package main\n" {
		t.Error("FixWithDiff should not modify files")
	}
}

func TestFixWithDiff_CompliantNoDiff(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.FixWithDiff(false)
	if len(result.Diffs) > 0 {
		t.Error("compliant file should produce no diff")
	}
}

// --- Remove ---

func TestRemove_StripsHeader(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.Remove(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "SPDX-License-Identifier") {
		t.Error("header should be removed")
	}
}

func TestRemove_NoHeader(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	eng, _ := New(testConfig(dir))
	result, _ := eng.Remove(false, false)
	if len(result.Fixed) > 0 {
		t.Error("no header = nothing to remove")
	}
}

func TestRemove_DryRun(t *testing.T) {
	dir := t.TempDir()
	original := "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n"
	createFile(t, dir, "main.go", original)
	eng, _ := New(testConfig(dir))
	result, _ := eng.Remove(true, false)
	if len(result.NonCompliant) != 1 {
		t.Error("expected 1 non-compliant in dry-run")
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != original {
		t.Error("dry-run should not modify files")
	}
}

func TestRemove_CrossFormat(t *testing.T) {
	dir := t.TempDir()
	apacheHeader := "// Copyright 2026 Acme Corp\n//\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//     http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an \"AS IS\" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\npackage main\n"
	createFile(t, dir, "main.go", apacheHeader)
	cfg := testConfig(dir)
	cfg.Format = "spdx"
	eng, _ := New(cfg)
	result, _ := eng.Remove(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "Apache License") {
		t.Error("Apache header should be stripped even with SPDX config")
	}
}

func TestRemove_CrossFormat_GPL(t *testing.T) {
	dir := t.TempDir()
	gplHeader := "// Copyright 2026 Acme Corp\n//\n// This program is free software: you can redistribute it and/or modify\n// it under the terms of the GNU General Public License as published by\n// the Free Software Foundation, either version 3 of the License, or\n// (at your option) any later version.\n//\n// This program is distributed in the hope that it will be useful,\n// but WITHOUT ANY WARRANTY; without even the implied warranty of\n// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n// GNU General Public License for more details.\n//\n// You should have received a copy of the GNU General Public License\n// along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\npackage main\n"
	createFile(t, dir, "main.go", gplHeader)
	cfg := testConfig(dir)
	cfg.Format = "reuse"
	eng, _ := New(cfg)
	result, _ := eng.Remove(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "GNU General Public License") {
		t.Error("GPL header should be stripped even with REUSE config")
	}
}

func TestRemove_CrossFormat_REUSE(t *testing.T) {
	dir := t.TempDir()
	reuseHeader := "// SPDX-FileCopyrightText: 2026 Acme Corp\n// SPDX-License-Identifier: MIT\n\npackage main\n"
	createFile(t, dir, "main.go", reuseHeader)
	cfg := testConfig(dir)
	cfg.Format = "spdx"
	eng, _ := New(cfg)
	result, _ := eng.Remove(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "SPDX-FileCopyrightText") {
		t.Error("REUSE header should be stripped even with SPDX config")
	}
}

// --- Fix with cross-format migration ---

func TestFix_MigratesApacheToSPDX(t *testing.T) {
	dir := t.TempDir()
	apacheHeader := "// Copyright 2025 OldCorp\n//\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//     http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an \"AS IS\" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\npackage main\n"
	createFile(t, dir, "main.go", apacheHeader)
	cfg := testConfig(dir)
	cfg.Format = "spdx"
	cfg.License = "MIT"
	cfg.CopyrightHolder = "NewCorp"
	eng, _ := New(cfg)
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	content := string(data)
	if strings.Contains(content, "Apache License") {
		t.Error("old Apache header should be replaced")
	}
	if !strings.Contains(content, "SPDX-License-Identifier: MIT") {
		t.Error("new SPDX header should be present")
	}
	if !strings.Contains(content, "Copyright 2026 NewCorp") {
		t.Error("new copyright should be present")
	}
}

func TestFix_MigratesGPLToReuse(t *testing.T) {
	dir := t.TempDir()
	gplHeader := "// Copyright 2025 OldCorp\n//\n// This program is free software: you can redistribute it and/or modify\n// it under the terms of the GNU General Public License as published by\n// the Free Software Foundation, either version 3 of the License, or\n// (at your option) any later version.\n//\n// This program is distributed in the hope that it will be useful,\n// but WITHOUT ANY WARRANTY; without even the implied warranty of\n// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n// GNU General Public License for more details.\n//\n// You should have received a copy of the GNU General Public License\n// along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\npackage main\n"
	createFile(t, dir, "main.go", gplHeader)
	cfg := testConfig(dir)
	cfg.Format = "reuse"
	cfg.License = "Apache-2.0"
	cfg.CopyrightHolder = "NewCorp"
	eng, _ := New(cfg)
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	content := string(data)
	if strings.Contains(content, "GNU General Public License") {
		t.Error("old GPL header should be replaced")
	}
	if !strings.Contains(content, "SPDX-FileCopyrightText: 2026 NewCorp") {
		t.Error("new REUSE header should be present")
	}
}

func TestFix_MigrateThenCheck(t *testing.T) {
	dir := t.TempDir()
	// Start with Apache header
	apacheHeader := "// Copyright 2025 OldCorp\n//\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//     http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an \"AS IS\" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\npackage main\n"
	createFile(t, dir, "main.go", apacheHeader)
	cfg := testConfig(dir)
	cfg.Format = "spdx"
	cfg.License = "MIT"
	cfg.CopyrightHolder = "NewCorp"
	// Fix: migrate Apache → SPDX
	eng, _ := New(cfg)
	eng.Fix(false, false)
	// Check: should now be compliant
	eng2, _ := New(cfg)
	result, _ := eng2.Check(false)
	if len(result.NonCompliant) > 0 {
		data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
		t.Errorf("after migration fix, check should pass; file content:\n%s", data)
	}
}

func TestFix_MigrateMultipleFormats(t *testing.T) {
	dir := t.TempDir()
	// One file with Apache header
	apacheHeader := "// Copyright 2025 OldCorp\n//\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//     http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an \"AS IS\" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\npackage main\n"
	createFile(t, dir, "apache.go", apacheHeader)
	// One file with REUSE header
	createFile(t, dir, "reuse.go", "// SPDX-FileCopyrightText: 2025 OldCorp\n// SPDX-License-Identifier: MIT\n\npackage main\n")
	// One file with no header
	createFile(t, dir, "bare.go", "package main\n")

	cfg := testConfig(dir)
	cfg.Format = "spdx"
	cfg.License = "Apache-2.0"
	eng, _ := New(cfg)
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 3 {
		t.Errorf("expected 3 fixed, got %d", len(result.Fixed))
	}
	// All should now pass check
	eng2, _ := New(cfg)
	result2, _ := eng2.Check(false)
	if len(result2.NonCompliant) > 0 {
		t.Errorf("after fixing all formats, %d files still non-compliant", len(result2.NonCompliant))
	}
}

// --- Parallel ---

func TestParallel_ManyFiles(t *testing.T) {
	dir := t.TempDir()
	for i := range 50 {
		name := fmt.Sprintf("file_%02d.go", i)
		createFile(t, dir, name, "package main\n")
	}
	cfg := testConfig(dir)
	eng, _ := New(cfg)
	result, err := eng.Fix(false, false)
	if err != nil {
		t.Fatal(err)
	}
	// All files should be fixed
	if len(result.Fixed) == 0 {
		t.Error("expected files to be fixed")
	}
	// Check with fresh engine
	eng2, _ := New(cfg)
	result2, _ := eng2.Check(false)
	if len(result2.NonCompliant) > 0 {
		t.Errorf("after parallel fix, %d still non-compliant", len(result2.NonCompliant))
	}
}

func TestParallel_SmallBatch(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "a.go", "package main\n")
	createFile(t, dir, "b.go", "package main\n")
	cfg := testConfig(dir)
	eng, _ := New(cfg)
	result, _ := eng.Fix(false, false)
	if len(result.Fixed) != 2 {
		t.Errorf("expected 2 fixed, got %d", len(result.Fixed))
	}
}

// --- Engine creation ---

func TestNew_InvalidFormat(t *testing.T) {
	cfg := testConfig(t.TempDir())
	cfg.Format = "nonexistent"
	if _, err := New(cfg); err == nil {
		t.Error("expected error")
	}
}

func TestNew_CustomWithoutTemplate(t *testing.T) {
	cfg := testConfig(t.TempDir())
	cfg.Format = "custom"
	cfg.HeaderTemplate = "/nonexistent/template.tmpl"
	if _, err := New(cfg); err == nil {
		t.Error("expected error")
	}
}
