// Copyright 2026 Chalindu Kodikara
// SPDX-License-Identifier: Apache-2.0

package engine

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chalindukodikara/licenseops/internal/config"
)

// helper to create a file in a temp dir.
func createFile(t *testing.T, dir, relPath, content string) string {
	t.Helper()
	full := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return full
}

func testConfig(dir string) config.Config {
	t := true
	return config.Config{
		License:         "Apache-2.0",
		CopyrightHolder: "Acme Corp",
		Year:            "2026",
		Format:          "spdx",
		Paths:           []string{dir},
		SkipGenerated:   &t,
		Gitignore:       &t,
		Exclude: []string{
			"vendor/**",
			"node_modules/**",
			".git/**",
		},
	}
}

// --- Check ---

func TestCheck_AllCompliant(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	createFile(t, dir, "lib.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) > 0 {
		t.Errorf("expected 0 non-compliant, got %d: %v", len(result.NonCompliant), result.NonCompliant)
	}
}

func TestCheck_NonCompliant(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "good.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	createFile(t, dir, "bad.go", "package main\n\nfunc main() {}\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant, got %d", len(result.NonCompliant))
	}
}

func TestCheck_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "gen.go", "// Code generated by tool. DO NOT EDIT.\npackage gen\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) > 0 {
		t.Error("generated files should be skipped, not reported as non-compliant")
	}
	if len(result.Skipped) != 1 {
		t.Errorf("expected 1 skipped, got %d", len(result.Skipped))
	}
}

func TestCheck_SkipsUnsupportedFiles(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "data.json", `{"key": "value"}`)

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) > 0 {
		t.Error("unsupported files should not be reported as non-compliant")
	}
}

// --- Fix ---

func TestFix_AddsHeaders(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Fix(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}

	// Verify the file now has a header
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if !strings.Contains(string(data), "SPDX-License-Identifier: Apache-2.0") {
		t.Error("file should have SPDX header after fix")
	}
}

func TestFix_LeavesCompliantUnchanged(t *testing.T) {
	dir := t.TempDir()
	original := "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n"
	createFile(t, dir, "main.go", original)

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Fix(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) > 0 {
		t.Error("compliant file should not be fixed")
	}

	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != original {
		t.Error("compliant file should be unchanged")
	}
}

func TestFix_DryRun(t *testing.T) {
	dir := t.TempDir()
	original := "package main\n"
	createFile(t, dir, "main.go", original)

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Fix(true, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant in dry-run, got %d", len(result.NonCompliant))
	}

	// File should NOT be modified
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != original {
		t.Error("dry-run should not modify files")
	}
}

func TestFix_ThenCheck(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	createFile(t, dir, "lib.go", "package main\n")

	cfg := testConfig(dir)

	// Fix first
	eng, _ := New(cfg)
	_, err := eng.Fix(false, false)
	if err != nil {
		t.Fatal(err)
	}

	// Then check — should pass
	eng2, _ := New(cfg)
	result, err := eng2.Check(false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) > 0 {
		t.Errorf("after fix, check should find 0 non-compliant, got %d", len(result.NonCompliant))
	}
}

func TestFix_MultipleFormats(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n")
	createFile(t, dir, "script.py", "print('hello')\n")
	createFile(t, dir, "query.sql", "SELECT 1;\n")

	cfg := testConfig(dir)
	cfg.License = "MIT"
	cfg.CopyrightHolder = ""
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Fix(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) != 3 {
		t.Errorf("expected 3 fixed, got %d: %v", len(result.Fixed), result.Fixed)
	}

	// Check each uses correct comment style
	goData, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if !strings.HasPrefix(string(goData), "// SPDX-License-Identifier: MIT") {
		t.Error("Go file should use // comments")
	}
	pyData, _ := os.ReadFile(filepath.Join(dir, "script.py"))
	if !strings.HasPrefix(string(pyData), "# SPDX-License-Identifier: MIT") {
		t.Error("Python file should use # comments")
	}
	sqlData, _ := os.ReadFile(filepath.Join(dir, "query.sql"))
	if !strings.HasPrefix(string(sqlData), "-- SPDX-License-Identifier: MIT") {
		t.Error("SQL file should use -- comments")
	}
}

// --- Remove ---

func TestRemove_StripsHeader(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Remove(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}

	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "SPDX-License-Identifier") {
		t.Error("header should be removed")
	}
	if !strings.Contains(string(data), "package main") {
		t.Error("code should be preserved")
	}
}

func TestRemove_NoHeader(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Remove(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) > 0 {
		t.Error("file with no header should not be modified")
	}
}

func TestRemove_DryRun(t *testing.T) {
	dir := t.TempDir()
	original := "// Copyright 2026 Acme Corp\n// SPDX-License-Identifier: Apache-2.0\n\npackage main\n"
	createFile(t, dir, "main.go", original)

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Remove(true, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.NonCompliant) != 1 {
		t.Errorf("expected 1 non-compliant in dry-run, got %d", len(result.NonCompliant))
	}

	// File should NOT be modified
	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if string(data) != original {
		t.Error("dry-run should not modify files")
	}
}

func TestRemove_PreservesShebang(t *testing.T) {
	dir := t.TempDir()
	createFile(t, dir, "script.py", "#!/usr/bin/env python3\n\n# Copyright 2026 Acme Corp\n# SPDX-License-Identifier: Apache-2.0\n\nprint('hello')\n")

	cfg := testConfig(dir)
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Remove(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}

	data, _ := os.ReadFile(filepath.Join(dir, "script.py"))
	content := string(data)
	if !strings.HasPrefix(content, "#!/usr/bin/env python3") {
		t.Error("shebang should be preserved")
	}
	if strings.Contains(content, "SPDX-License-Identifier") {
		t.Error("header should be removed")
	}
}

func TestRemove_CrossFormat(t *testing.T) {
	// Remove should strip ANY format, not just the configured one
	dir := t.TempDir()
	// File has Apache long-form header, but config uses SPDX format
	apacheHeader := "// Copyright 2026 Acme Corp\n//\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//     http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an \"AS IS\" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\npackage main\n"
	createFile(t, dir, "main.go", apacheHeader)

	cfg := testConfig(dir)
	cfg.Format = "spdx" // Config uses SPDX, but file has Apache
	eng, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}

	result, err := eng.Remove(false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Fixed) != 1 {
		t.Errorf("expected 1 fixed, got %d", len(result.Fixed))
	}

	data, _ := os.ReadFile(filepath.Join(dir, "main.go"))
	if strings.Contains(string(data), "Apache License") {
		t.Error("Apache header should be stripped even with SPDX config")
	}
}

// --- Engine creation ---

func TestNew_InvalidFormat(t *testing.T) {
	cfg := testConfig(t.TempDir())
	cfg.Format = "nonexistent"
	_, err := New(cfg)
	if err == nil {
		t.Error("expected error for invalid format")
	}
}

func TestNew_CustomWithoutTemplate(t *testing.T) {
	cfg := testConfig(t.TempDir())
	cfg.Format = "custom"
	cfg.HeaderTemplate = "/nonexistent/template.tmpl"
	_, err := New(cfg)
	if err == nil {
		t.Error("expected error for missing custom template")
	}
}
